### ISSUE TITLE
Fail when deploy to aws lambda using serverless

### ISSUE THREAD

**Issue by zluo01** [Blazity/next-image-proxy#2]
Hi, when I deploy my app to aws lambda using serverless nextjs. API will fail with 500 error in the image component with following message. Wonder what can be the cause ? Thanks.

```
"url" parameter is valid but upstream response is invalid
```

payload:
```
url=%2Fapi%2Fproxy%2Fimage%3FimageUrl%3Dhttps%3A%2F%2Fp2.music.126.net%2F3I-73aQn3YCw-2cZdK1fQw%3D%3D%2F109951166027478939.jpg%3Fparam%3D250y250&w=640&q=75
```

sample logs:
```
ERROR	Error processing upstream response due to error for key:  ...... Stack trace: TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'IncomingMessage'
    |     property 'req' -> object with constructor 'ClientRequest'
    --- property 'res' closes the circle
    at JSON.stringify (<anonymous>)
    at AwsPlatformClient.getObject (/var/task/index.js:110442:22)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async imageOptimizer (/var/task/index.js:92662:30)
    at async Runtime.handler (/var/task/index.js:110616:9)

```

**Comment by bmstefanski** [comment]
Hi @zluo01, thanks for the issue and sorry for the late response. Were you able to resolve the issue? I've no experience with AWS-hosted Next.js apps, so the error doesn't tell me much. What's weird is, that it should work on AWS Lambda because that's the case with Vercel and AFAIK they're also using it, so I am guessing it's something with serverless-nextjs library

**Comment by zluo01** [comment]
I think the problem can due to aws lambda right now does not support Node.js data streaming yet.
